name: Main Taski Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name:
        Check out code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name:  Install dependecies
        run: |
          pyhton -m pip install --upgrade pip
          python -r install flake8==6.0.0 flake8-isort==6.0.0
      - name: Test with flake8
        run python -m flake8 backend/